### ISSUE TITLE
Re-add manuafactures logo at cpu meter

### ISSUE THREAD

**Issue by Siggi0904** [SilverAzide/Modernizer#1]
Hi,

can you re add the manufactures brand logo at cpu meter please?

with modernizer:
![grafik](https://user-images.githubusercontent.com/4992106/192483582-4c9826e3-8f76-493e-8338-1fadc31cf8ce.png)

Before:
![grafik](https://user-images.githubusercontent.com/4992106/192483686-1150d909-87a4-46d7-8712-4281d35ffcaf.png)

Great thanks.

**Comment by SilverAzide** [comment]
Well, using generic "flat" logos is kind of the point of the whole "modern" look.  But luckily you can easily switch this back if you want (I prefer the brand logos too, TBH 😉).

Navigate to your Rainmeter skins folder, and open the Gadgets\@Resources\CpuVariables.inc file with a text editor.  Set the following variable, like so:
```ini
UseGenericIcons=0
```
Refresh the skin and you should be good to go!

**Comment by Siggi0904** [comment]
Okay, I asked because of the GPU meter gadget has the brand logo from the NVIDIA graphics card.
With this point, I thin it was missed at the CPU meter.

Thanks, I'll test your advice.

**Comment by SilverAzide** [comment]
Yes, you're right.... I really reeeeeeally didn't want to change the GPU Meter icon.  So I convinced myself they were "flat enough" and skipped it.  😄  Hopefully no one will mind too much.  It's pretty easy to switch this to generic colored icons, if someone wants it.

**Comment by Siggi0904** [comment]
Okay, thanks for the info.
Then, all is clear. 

Another question.
I saw, that the time for uptime between logon is quite short.
And the logon time differs to the real logon time to my local account.
Is there any known bug for these times?

Thanks.

**Comment by SilverAzide** [comment]
Good question!  These two values are coming from two Rainmeter measures:  SysInfo (USER_LOGONTIME) and Uptime.  They are showing values for me today that are about ~3 minutes apart, which I think is about right.  I'm not sure where/how Rainmeter is getting the logon time; I recall when the SysInfo logon time was added that this was a complicated value to obtain.  If I recall correctly, I think they are getting this value from the Event log, so it can easily differ from your actual local logon time by some amount.  The "net user <username>" command doesn't work for AD accounts, and the AD commands don't work for local accounts, so I think that is why they are using the Event log.

You can probably get better info posting this on the Rainmeter forums; the Chronometer skin is just showing what Rainmeter is reporting, so there's not much I can do if it looks off.

**Comment by Siggi0904** [comment]
thanks for the Info. But I have the same 3minutes beteen uptime and logon. We're working at same time schedule. :-D

But Rainmeter wrote in there docs, it is better to use the SysInfo plugin up from windows 10 for the login time.
Because of that, can you check the usage of these sysinfo plugin?
See: https://docs.rainmeter.net/manual/measures/uptime/

And you commented this topic in the forum too :-) https://forum.rainmeter.net/viewtopic.php?t=27456

Thanks.

**Comment by Siggi0904** [comment]
And I don't know if this following topic is up to date, but same problem, I think.

See: https://forum.rainmeter.net/viewtopic.php?t=17680

**Comment by SilverAzide** [comment]
Gotcha... but I'm not sure I'm following you now.  Are you implying that there a problem?

The Digital Clock skin uses the exact code you referenced above in jsmorley's USER_LOGONTIME post.  This feature was added to Rainmeter after a long discussion on the Forums between myself and others on how to get this value reliably, and jsmorley came up with a way to add it to Rainmeter natively.  The Digital Clock skin was using the QUSER command to get this value prior to it being added to Rainmeter (Gadgets 4.0.0 was the first version to use this new feature, back in 2018).

The caution with hybrid shutdowns is still valid; there is nothing that can be done about that.  The docs include ways to do full shutdowns, and you can turn this off completely if you wanted.

Let me know what your concerns are.

**Comment by Siggi0904** [comment]
hm, thanks for the explanation.

But actually I think the values are wrong.
Uptime is correct, I think. But logon time not.

If I start my pc and wait with login arround 5 minutes the gaget shows only 3 minutes.
In these case, this point should be checked and should be corrected, if possible.

If it is not possible, then I'll close these gadget and work without these information's.
It's not a problem, but other ueser could ask too.

Great thanks.

**Comment by SilverAzide** [comment]
Oh, I see... well, I'm not sure I can help you.  This would be a question for the Rainmeter devs.  The skin is just reporting what Rainmeter says is the logon time.

If you don't want to see the logon tine, you can just turn it off.  Click the wrench icon to open the Settings and uncheck the "Show Logon Time" option.

You can try looking at other tools to confirm the data if you like, but in my case it is agreeing almost exactly.   Go to `Rainmeter > About > Skins` and select the `Chronometer` skin.  Scroll down until you see the measure `MeasureUserLogonTime`.  This will show the time Windows says you logged on.  You can compare this to the `quser` command to see if there is a difference, although this isn't quite as exact down to the second.  There are other ways to get this as well if you have a domain account (using AD).

![logon](https://user-images.githubusercontent.com/2706567/193025258-ffe3d855-6ae4-452f-baed-88aaf90e6722.png)

If you log off and log back on, you should see the new logon time.

**Comment by Siggi0904** [comment]
hm, I'm not 100% familiar with with these datas.
I only saw in the forum, that values from the sysinfo plugin are better.

If you can check these topic with rainmeter devs. I'll be happier.
Because, I dont know all the backgtound what is needed.

Thanks.

**Comment by Siggi0904** [comment]
And these are my actual datas. That's not possible because I had wait around 2-4 minutes to login,
I was in an other room after switching on my PC

![grafik](https://user-images.githubusercontent.com/4992106/193111301-7ac7cadf-69de-4cd2-b2cc-7411451ffa63.png)

**Comment by SilverAzide** [comment]
OK! Well, I'm not sure what to tell you.  As I mentioned earlier, that logon date you see ***is*** the SysInfo plugin data.  That's the only way in Rainmeter to get that value.  It should match the QUSER command output.  That's when Windows thinks was the time you logged on, so I'm not sure what more I can say...
